### ISSUE TITLE
Add 'wordWrap' formatter

### ISSUE THREAD

**Issue by chshersh** [cdornan/fmt#14]
Something like that:

```haskell
wordsWrapF :: Int -> Text -> Builder
```

Behavior should be the following: 

1. Splits given text into lines with length no more than given `Int`.
2. No breaks in the middle of the words (every line should contain whole words).

TODO: should we compress consequent spaces? 
Like, should 

```haskell
wordWrapF 100 "foo            bar"
```

result in 

```haskell
"foo bar"
```
? 

I think it should.

@neongreen Please, comment.

Also, relevant to https://github.com/serokell/importify/issues/90

**Comment by cdornan** [comment]
If anybody still thinks this is important then reopen, or better submit a patch.
