### ISSUE TITLE
Add utf8F and so on?

### ISSUE THREAD

**Issue by neongreen** [cdornan/fmt#19]

**Comment by neongreen** [comment]
I don't think there's much point in adding the whole flock -- just `utf8F` and `latin1F`. @ChShersh would you mind doing that?

**Comment by ChShersh** [comment]
@neongreen I don't mind. But you could you guide on some information regarding packages for such formatters? I don't really understand how this is different from `id :: Text -> Text`.

**Comment by neongreen** [comment]
```haskell
utf8F :: ByteString -> Builder
latin1F :: ByteString -> Builder
```

I.e. they decode bytestrings into text (which can be done in different ways).

We would also need classes for them (like with base64) to support both strict and lazy variants.

**Comment by ChShersh** [comment]
@neongreen Okay, I can try to do this.

**Comment by cdornan** [comment]
I have experimented with this on a private fork (for many months) and concluded in the end that it really wasn't worth the complexity.
