### ISSUE TITLE
0 of unsigned type is printed incorrectly

### ISSUE THREAD

**Issue by gromakovsky** [cdornan/fmt#31]
Run `stack repl` in a fresh clone of this repo:
```
ghci> pretty (0 :: Word) :: String
"-0"
```

That's a known problem in `formatting` that's resolved in this PR: https://github.com/chrisdone/formatting/pull/61/files. However, `formatting` is not maintained anymore, but is still used as a dependency. As a long term solution I think this dependency should be removed somehow, but in short term it would be nice to fix formatting of unsigned numbers at least.

**Comment by gromakovsky** [comment]
`formatting` got a maintainer and this issue was fixed there. So updating `formatting` dependency should fix the problem.

**Comment by cdornan** [comment]
Fixed in formatting-7.0.0 &mdash; the cabal lower bounds have been adjusted accordingly.
