### ISSUE TITLE
Try the |< >| IO idea

### ISSUE THREAD

**Issue by neongreen** [cdornan/fmt#5]
https://www.reddit.com/r/haskell/comments/647qfj/fmt_a_new_formatting_library/dg0d2az/

> For the IO thing I see two options
>
> 1) `fmt |< action = fmap (\result -> print $ fmt <> result) action`
> 2) `fmt |< action = print fmt >> action`
>
> The first is closer to what you said..but the second has clearer order of effects.

**Comment by cdornan** [comment]
Closing because I think we have moved on &mdash; please reopen if you still think it is relevant.
